// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp8XWef0_aSn0Tg0XR4ynuRGfB5A61rI',
    appId: '1:374946187150:web:e399256c3eddd7e1c606df',
    messagingSenderId: '374946187150',
    projectId: 'muhamah-app',
    authDomain: 'muhamah-app.firebaseapp.com',
    storageBucket: 'muhamah-app.firebasestorage.app',
    measurementId: 'G-Z9S99B1755',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_UR5B8LT1I7RKTXlC3d649v7e2q9Ufmg',
    appId: '1:374946187150:android:60dba812e5a4793ec606df',
    messagingSenderId: '374946187150',
    projectId: 'muhamah-app',
    storageBucket: 'muhamah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ157Kw2yWYmG-aGT3KKwTRCQbbKQoGKQ',
    appId: '1:374946187150:ios:5e942c72ed6f0efdc606df',
    messagingSenderId: '374946187150',
    projectId: 'muhamah-app',
    storageBucket: 'muhamah-app.firebasestorage.app',
    iosBundleId: 'com.example.mahamikFlutterSource',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ157Kw2yWYmG-aGT3KKwTRCQbbKQoGKQ',
    appId: '1:374946187150:ios:5e942c72ed6f0efdc606df',
    messagingSenderId: '374946187150',
    projectId: 'muhamah-app',
    storageBucket: 'muhamah-app.firebasestorage.app',
    iosBundleId: 'com.example.mahamikFlutterSource',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRp8XWef0_aSn0Tg0XR4ynuRGfB5A61rI',
    appId: '1:374946187150:web:06b8a0cc1c602a31c606df',
    messagingSenderId: '374946187150',
    projectId: 'muhamah-app',
    authDomain: 'muhamah-app.firebaseapp.com',
    storageBucket: 'muhamah-app.firebasestorage.app',
    measurementId: 'G-TKY5EJD316',
  );
}
